[build]
#  command = "gatsby clean && npm run build"  
  command = "npm rebuild @parcel/watcher && gatsby build"
  publish = "public"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10.8.2"
